# This is a basic workflow to help you get started with Actions

name: r

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: update
  # schedule:
  #   - cron:  '*/30 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [3.5, 3.6]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3
        with:
          r-version: ${{ matrix.r-version }}
    - name: Setup branch  
      run: |
          git config --global user.name 'Manuelfjr'
          git config --global user.email 'ferreira.jr.ufpb@gmail.com'
          git fetch
        
    - name: Deployment
      run: |
          Rscript deploy.R
    
    - name: Commit and push  
      run: |
          git add -A
          git commit -am "update: Deployment"
          git push
      
#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.